version: "3.9"

services:
  # Run build task in dev environment for api so watching files works.

  db:
    image: "mongo"
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 1234
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - senphor-mongo:/data/db

volumes:
  senphor-mongo:
    external: false
