version: "3.9"

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: "mongo"
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 1234
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - senphor-mongo:/data/db

volumes:
  senphor-mongo:
    external: false
